FORMAT: 1A
HOST: http://www.google.com

# Is The Internet Going Down Now?
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Notes
Notes related resources of the **Notes API**

## Root State [/]
### Check state of the internet [GET]
+ Response 200 (text/plain)

        No
