FORMAT: 1A
HOST: http://www.gravatar.com

# Gravatar

# Group Avatar

## Notes Collection [/notes/{?param1,param2,param3}]

+ Parameters

    + param1 (optional, string, `aaz`) ... param1 is aaz
    + param2 (optional, string, `vvv`) ... param2 is vvv

### here [GET]
+ Response 200

        == Here be lions ==
    

## Image Collection [/avatar/{hash}.jpg{?id,query}]
Whatever is a Gravatar, it lives...

+ Parameters

    + id (string) ... whatever
    + hash (string, `ba9e69315d0f4460caae5242bb93c745`) ... The md5 hash of lower-cased email address
    + query (string, `d=mm`) ... the query to tweak the returned image

### Does it exist? [HEAD]
+ Response 200

    + Headers

            Content-type: image/jpeg
            Content-Length: 1000
            Server: nginx

### Update an avatar [POST]
+ Request

        call me

+ Response 200

        called with 200

### Retrieve an avatar [GET]
+ Parameters

    + aa (aa) ... aa
    + iii (string) ... aaaa
    + hash (string, `1234567890`) ... The md5 hash of lower-cased email address
    + hashme (string, `bbb`) ... trrrt
    + aaa (aaa) ... bbb

+ Response 200
All is there

    + Body

            [binary content]
